[project]
name = "emstencil"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyodbc>=5.3.0",
    "pyside6>=6.10.1",
    "sxl>=0.0.1a10",
]

[dependency-groups]
dev = [
    "nuitka>=2.8.9",
    "pytest>=9.0.1",
]
